import GlobalButton from '@/components/button'
import ComentaryCard from '@/components/commentaryCard'
import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Recon | Suporte ao cliente</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* googleFonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet"></link>
      </Head>

      <main className='w-screen h-screen justify-center items-center font-primary lg:bg-desktop lg:bg-center lg:bg-cover lg:bg-no-repeat lg:min-h-screen lg:h-full lg:text-center'>
        <div className="flex w-screen lg:hidden">
          <Image
          width={1024} 
          height={500}
          className='w-screen' 
          src={'/assets/bgMobile.png'} 
          alt='Imagem publicitária da recon' 
          />
        </div>

        <div className="flex flex-col w-screen gap-12 lg:justify-center lg:items-center">
          <div className="flex flex-col gap-2 mt-8 text-center lg:w-1/3">
            <h1 className='font-semibold text-xl'>Olá usuário</h1>
            <p className='font-semibold text-xs px-28'>Seja bem vindo ao suporte do Recon APP</p>
          </div>

          <ComentaryCard />

          <div className="flex justify-center pb-20 lg:w-1/3">
            <GlobalButton label='Preencher Formulário' />
          </div>
        </div>
      </main>
    </>
  )
}
